  name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Ou outra branch, se estiver usando uma diferente
  pull_request:
    branches:
      - main  # Ou outra branch, se estiver usando uma diferente

jobs:
  sonarcloud:
    runs-on: ubuntu-latest  # Ou outra plataforma de sua escolha

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2  # Faz o checkout do código do repositório

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # ou 'adoptopenjdk'
          java-version: '17'  # Versão do Java compatível com seu projeto

      - name: Rodar análise com SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Certifique-se de que o token está configurado no Secrets do GitHub
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli.zip
          ./sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
            -Dsonar.organization=santos1979 \
            -Dsonar.projectKey=machine-learning-projects \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io
